const PREFIX = 'Payment/';

/*
    PAYMENT ACTION (pay now and modify payment plan)
    - when come to payment page by click payment button
      which locates at Reservation detail page action bar
*/

export const PAYMENTACTIONS_UPDATE_PAYMENT_TYPE_ON_MODIFICATION = `${PREFIX}UPDATE_PAYMENT_TYPE_ON_MODIFICATION`;

// ---PAYMENT/PAYMENTFOOTER-----------------------------------------------
export const PAYMENTFOOTER_CANCEL_MAKE_A_PAYMENT = `${PREFIX}CANCEL_MAKE_A_PAYMENT`;
export const PAYMENTFOOTER_CANCEL_MAKE_A_PAYMENT_SUCCESS = `${PREFIX}CANCEL_MAKE_A_PAYMENT_SUCCESS`;
export const PAYMENTFOOTER_CANCEL_MAKE_A_PAYMENT_FAILURE = `${PREFIX}CANCEL_MAKE_A_PAYMENT_FAILURE`;
export const PAYMENTFOOTER_SAVE_MODIFIED_PAYMENTPLAN = `${PREFIX}PAYMENTFOOTER_SAVE_MODIFIED_PAYMENTPLAN`;
export const PAYMENTFOOTER_SAVE_MODIFIED_PAYMENTPLAN_SUCCESS = `${PREFIX}PAYMENTFOOTER_SAVE_MODIFIED_PAYMENTPLAN_SUCCESS`;
export const PAYMENTFOOTER_SAVE_MODIFIED_PAYMENTPLAN_FAILURE = `${PREFIX}PAYMENTFOOTER_SAVE_MODIFIED_PAYMENTPLAN_FAILURE`;
