os: osx
language: node_js
cache:
  directories:
    - node_modules
    - $HOME/Library/Caches/Homebrew
node_js:
  - 'lts/*'
before_install:
  - npm install 
  - git pull
script:
  - npm run build
after_success:
  - git config user.email "travis@travis.org"
  - git config user.name "travis"
  - git checkout gh-pages
  - git pull origin gh-pages:gh-pages
  - ls|grep -v 'node_module'|grep -v 'buildBook'|xargs rm -rf
  - mv buildBook/.** ./ || mv buildBook/** ./ 
  - rm -rf buildBook
  - git add ./
  - git commit --allow-empty -m "deploy gitbook"
  - git push https://clownvary:${GITHUB_API_KEY}@${GH_REF} HEAD:gh-pages