os: osx
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 'lts/*'
before_install:
  - git pull
install:
  - npm install
  - brew install tree
script:
  - npm run updateReadme
after_success:
  - git config user.email "travis@travis.org"
  - git config user.name "travis"
  - git add README.md
  - git commit --allow-empty -m "updated README.md"
  - git push https://clownvary:${GITHUB_API_KEY}@${GH_REF} HEAD:master