language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 'lts/*'
install:
  - npm install
script:
  - npm run updateReadme
  - git add README.md
  - git commit --allow-empty -m "updated README.md"
