export default {
  ACTIVITY_ENROLLMENT_REGULAR: 0,
  ACTIVITY_ENROLLMENT_TEAM_GROUP: 1,
  ACTIVITY_ENROLLMENT_PRIVATE_LESSON: 2,
  ACTIVITY_ENROLLMENT_PACKAGE: 3,
  PROGRAM_ENROLLMENT: 4,
  MEMBERSHIP_SALE: 5,
  GIFT_CERTIFICATE: 6,
  DONATION: 7,
  MERCHANDISE_SALE: 8,
  OUTSTANDING_BALANCE_PAYMENT: 9,
  ACTIVITY_ENROLLMENT_WAITLIST: 10,
  USAGE_FEE: 11,
  REFUND: 12,
  TRANSFER_IN: 13,
  TRANSFER_OUT: 14,
  MEMBERSHIP_RENEWAL: 15
};
