export default {
  HAS_AVAILABLE_AND_ENROLLED: 1, // show enrolled label
  HAS_AVAILABLE_AND_WAITLISTED: 2, // show waitlisted label
  HAS_AVAILABLE_AND_ENROLLED_AND_WAITLISTED: 3, // show enrolled/waitlisted label
  HAS_AVAILABLE_AND_FULL: 4, // show Partially Full label
  HAS_AVAILABLE_AND_FULL_ALLOWWAITLIST: 5, // selected show Waiting List
  HAS_AVAILABLE_AND_ENROLLED_FULL_NOT_ALLOWWAITLIST: 6,
  HAS_AVAILABLE_AND_WAITLISTED_FULL_NOT_ALLOWWAITLIST: 7,
  HAS_AVAILABLE_AND_WAITLISTED_FULL_ENROLLED_NOT_ALLOWWAITLIST: 8,
  ENROLLED_AND_FULL_ALLOWWAITLIST: 9,
  WAITLISTED_AND_FULL_ALLOWWAITLIST: 10,
  WAITLISTED_FULL_ENROLLED_ALLOWWAITLIST: 11,
  FULL_NO_AVAILABLE_ALLOWWAITLIST: 12
}