const PREFIX = 'Master/';

export const MASTER_UI_SHOPPINGCART_COUNT = `${PREFIX}MASTER_UI_SHOPPINGCART_COUNT`;
export const MASTER_ON_SHOW_MENU = `${PREFIX}MASTER_ON_SHOW_MENU`;
export const MASTER_ON_HIDE_NAVIGATION = `${PREFIX}MASTER_ON_HIDE_NAVIGATION`;
export const MASTER_ON_ANIMATION_END = `${PREFIX}MASTER_ON_ANIMATION_END`;
export const MASTER_ON_EXPAND_SECONDARY_MENU = `${PREFIX}MASTER_ON_EXPAND_SECONDARY_MENU`;
