const bookingInfo = {
  eventTypes: [],
  scheduleTypes: [],
  prepCodeList: [],
  setUpList: [],
  cleanUpList: [],
  permitBookingList: [
    {
      setupMinutes: 3,
      definedDateRange: [
        {
          rentalBlockID: 0,
          startEventTime: "2:00 AM",
          bookingAssignment: 0,
          reservationType: 0,
          resourceBookingID: 0,
          startEventDate: "2016 Dec 21",
          attendance: 2,
          dateRangeID: 0,
          isDeleteSchedule: false,
          endEventTime: "3:00 AM",
          endEventDate: "2016 Dec 21",
          pendingID: "pending_775_7159",
          startEventDatetime: "12/21/2016 2:00 AM",
          ownerPendingReceipt: true,
          transactionID: -1,
          endEventDatetime: "12/21/2016 3:00 AM"
        }
      ],
      resourceType: 0,
      resourceID: 1,
      rentalBlock: [],
      bookingDetail: [],
      eventTypeID: 6,
      reservationPeriodUnit: 2,
      eventType: "event type 1",
      prepCodeID: 10,
      resourceNumber: "1",
      resourceName: "resourceName 1",
      cleanupMinutes: 5
    }
  ],
  pendingBookingList: [
    {
      setupMinutes: 0,
      definedDateRange: [
        {
          id: 3,
          name: "2016 Jun 01 to 2016 Jun 03",
          selected: true,
          parent_id: 4,
          text: "2016 Jun 01 to 2016 Jun 03",
          value: 3
        }
      ],
      resourceType: "",
      resourceID: 2,
      rentalBlock: [],
      bookingDetail: [
        {
          endScheduleDate: "2016 Jun 7",
          setupMinutes: 30,
          startScheduleDay: "Tue",
          rentalBlockID: -1,
          startScheduleDatetiem: "2016 Jun 4 8:00 PM",
          permitNumber: 349,
          eventName: "1 f+expiration kaely eventName &amp;",
          startEventTime: "1:00 AM",
          bookingAssignment: 0,
          reservationType: 0,
          resourceBookingID: 8622,
          startEventDate: "2016 Jun 5",
          startScheduleTime: "8:00 PM",
          eventNotes: "aa",
          startScheduleDate: "2016 Jun 4",
          resourceType: 0,
          companyName: "MM companyName",
          reservationScope: "Normal",
          resourceID: 2,
          permitDate: "2016 Jun 1",
          attendance: 3,
          customerName: "customer 1",
          endScheduleDay: "Tue",
          dateRangeID: 3,
          isDeleteSchedule: false,
          date_range: [
            {
              id: 3,
              name: "2016 Jun 01 to 2016 Jun 03",
              selected: true,
              parent_id: 4,
              text: "2016 Jun 01 to 2016 Jun 03",
              value: 3
            }
          ],
          endEventTime: "12:30 AM",
          scheduleTypeID: 3,
          endEventDate: "2016 Jun 7",
          permitStatus: 2,
          eventTypeId: 3,
          permitStatusDescription: "Approved",
          eventAttendace: 3,
          scheduleType: "scheduleType",
          reservationPeriodUnit: 6,
          pendingID: -1,
          rental_block: [
            {
              id: 2,
              name: "9:00 AM to 12:00 PM",
              selected: true,
              parent_id: 6
            }
          ],
          startEventDatetime: "",
          eventType: "event type 2",
          ownerPendingReceipt: true,
          isActivityIgnoreMaximum: true,
          permitID: -1,
          resourceNumber: "2",
          customerType: "customerType",
          transactionID: 36378,
          customerID: 32523,
          resourceName: "resourceName 2",
          endEventDatetime: "",
          cleanupMinutes: 30,
          reservationExpiration: "2016 Jun 4 expiration",
          endScheduleDatetiem: "2016 Jun 7 11:30 AM",
          endScheduleTime: "11:30 AM"
        },{
          endScheduleDate: "2016 Jun 7",
          setupMinutes: 30,
          startScheduleDay: "Tue",
          rentalBlockID: -1,
          startScheduleDatetiem: "2016 Jun 4 8:00 PM",
          permitNumber: 349,
          eventName: "bookingID=0,and pendingID>0",
          startEventTime: "1:00 AM",
          bookingAssignment: 0,
          reservationType: 0,
          resourceBookingID: 0,
          startEventDate: "2016 Jun 5",
          startScheduleTime: "8:00 PM",
          eventNotes: "aa",
          startScheduleDate: "2016 Jun 4",
          resourceType: 0,
          companyName: "MM companyName",
          reservationScope: "Normal",
          resourceID: 2,
          permitDate: "2016 Jun 1",
          attendance: 3,
          customerName: "customer 1",
          endScheduleDay: "Tue",
          dateRangeID: 3,
          isDeleteSchedule: false,
          date_range: [
            {
              id: 3,
              name: "2016 Jun 01 to 2016 Jun 03",
              selected: true,
              parent_id: 4,
              text: "2016 Jun 01 to 2016 Jun 03",
              value: 3
            }
          ],
          endEventTime: "12:30 AM",
          scheduleTypeID: 3,
          endEventDate: "2016 Jun 7",
          permitStatus: 2,
          eventTypeId: 3,
          permitStatusDescription: "Approved",
          eventAttendace: 3,
          scheduleType: "scheduleType",
          reservationPeriodUnit: 6,
          pendingID: 1,
          rental_block: [
            {
              id: 2,
              name: "9:00 AM to 12:00 PM",
              selected: true,
              parent_id: 6
            }
          ],
          startEventDatetime: "",
          eventType: "event type 2",
          ownerPendingReceipt: true,
          isActivityIgnoreMaximum: true,
          permitID: -1,
          resourceNumber: "2",
          customerType: "customerType",
          transactionID: 36378,
          customerID: 32523,
          resourceName: "resourceName 2",
          endEventDatetime: "",
          cleanupMinutes: 30,
          reservationExpiration: "2016 Jun 4 expiration",
          endScheduleDatetiem: "2016 Jun 7 11:30 AM",
          endScheduleTime: "11:30 AM"
        },{
          endScheduleDate: "2016 Jun 7",
          setupMinutes: 30,
          startScheduleDay: "Tue",
          rentalBlockID: -1,
          startScheduleDatetiem: "2016 Jun 4 8:00 PM",
          permitNumber: 349,
          eventName: "bookingID=0,and pendingID=0",
          startEventTime: "1:00 AM",
          bookingAssignment: 0,
          reservationType: 0,
          resourceBookingID: 0,
          startEventDate: "2016 Jun 5",
          startScheduleTime: "8:00 PM",
          eventNotes: "aa",
          startScheduleDate: "2016 Jun 4",
          resourceType: 0,
          companyName: "MM companyName",
          reservationScope: "Normal",
          resourceID: 2,
          permitDate: "2016 Jun 1",
          attendance: 3,
          customerName: "customer 1",
          endScheduleDay: "Tue",
          dateRangeID: 3,
          isDeleteSchedule: false,
          date_range: [
            {
              id: 3,
              name: "2016 Jun 01 to 2016 Jun 03",
              selected: true,
              parent_id: 4,
              text: "2016 Jun 01 to 2016 Jun 03",
              value: 3
            }
          ],
          endEventTime: "12:30 AM",
          scheduleTypeID: 3,
          endEventDate: "2016 Jun 7",
          permitStatus: 2,
          eventTypeId: 3,
          permitStatusDescription: "Approved",
          eventAttendace: 3,
          scheduleType: "scheduleType",
          reservationPeriodUnit: 6,
          pendingID: 'pending_775_7160',
          rental_block: [
            {
              id: 2,
              name: "9:00 AM to 12:00 PM",
              selected: true,
              parent_id: 6
            }
          ],
          startEventDatetime: "",
          eventType: "event type 2",
          ownerPendingReceipt: true,
          isActivityIgnoreMaximum: true,
          permitID: -1,
          resourceNumber: "2",
          customerType: "customerType",
          transactionID: 36378,
          customerID: 32523,
          resourceName: "resourceName 2",
          endEventDatetime: "",
          cleanupMinutes: 30,
          reservationExpiration: "2016 Jun 4 expiration",
          endScheduleDatetiem: "2016 Jun 7 11:30 AM",
          endScheduleTime: "11:30 AM"
        }
      ],
      eventTypeID: 3,
      reservationPeriodUnit: 6,
      eventType: "event type 2",
      prepCodeID: -1,
      resourceNumber: "2",
      resourceName: "resourceName 2",
      cleanupMinutes: 0
    },
    {
      setupMinutes: 3,
      definedDateRange: [
        {
          rentalBlockID: 0,
          startEventTime: "2:00 AM",
          bookingAssignment: 0,
          reservationType: 0,
          resourceBookingID: 0,
          startEventDate: "2016 Dec 21",
          attendance: 2,
          dateRangeID: 0,
          isDeleteSchedule: false,
          endEventTime: "3:00 AM",
          endEventDate: "2016 Dec 21",
          pendingID: "pending_775_7159",
          startEventDatetime: "12/21/2016 2:00 AM",
          ownerPendingReceipt: true,
          transactionID: -1,
          endEventDatetime: "12/21/2016 3:00 AM"
        }
      ],
      resourceType: 0,
      resourceID: 1,
      rentalBlock: [],
      bookingDetail: [],
      eventTypeID: 6,
      reservationPeriodUnit: 2,
      eventType: "event type 1",
      prepCodeID: 10,
      resourceNumber: "1",
      resourceName: "resourceName 1",
      cleanupMinutes: 5
    }
  ],
  error: {
    code: null,
    clientMessages: [],
    serverMessages: [],
    conflictMessage: "",
    entity: {
      eventName: false,
      scheduleTypeID: false,
      eventResource: [],
      overrideRentalBlockTimeError: []
    }
  },
  data: {
    permitID: -1,
    eventName: '',
    scheduleTypeID: -1,
    scheduleType: '',
    checkForWaitlistConflict: true,
    eventResource: [{
      "setupMinutes": 0,
      "isTemplate": true,
      "definedDateRange": [{
        "id": 3,
        "name": "2016 Jun 01 to 2016 Jun 03",
        "selected": false,
        "parent_id": 4,
        "text": "2016 Jun 01 to 2016 Jun 03",
        "value": 3
      }, {
        "id": 4,
        "name": "2016 Jun 16 to 2016 Jun 20",
        "selected": false,
        "parent_id": 1,
        "text": "2016 Jun 16 to 2016 Jun 20",
        "value": 4
      }],
      "resourceType": 0,
      "resourceID": 2,
      "baseBookingID": 2,
      "rentalBlock": [],
      "bookingDetail": [{
        "recurringPattern": 'recurring',
        "currentEvent": true,
        "recurringExceptions": [],
        "hasRecurring": false,
        "baseBookingID": "12",
        "rentalBlockID": 0,
        "recurringEnabled": false,
        "ignoreConflict": false,
        "startEventTime": "2:00 AM",
        "bookingAssignment": 0,
        "reservationType": 0,
        "resourceBookingID": 11,
        "startEventDate": "2016 Dec 21",
        "pendingRemoveFromRecurringGroup": "",
        "attendance": 2,
        "dateRangeID": 4,
        "recurringReservationGroupID": 0,
        "isDeleteSchedule": false,
        "endEventTime": "3:00 AM",
        "endEventDate": "2016 Dec 21",
        "reservationPeriodUnit": 6,
        "pendingID": "pending_775_7160",
        "isRecurring": false,
        "startEventDatetime": "12/21/2016 2:00 AM",
        "ignoreClosetime": false,
        "ownerPendingReceipt": true,
        "masterFacilityScheduleID": null,
        "transactionID": -1,
        "expanded": false,
        "endEventDatetime": "12/21/2016 3:00 AM",
        "ignoreSkipdate": false
      }],
      "eventTypeID": 36,
      "reservationPeriodUnit": 6,
      "eventType": "'South West Hub",
      "prepCodeID": -1,
      "resourceNumber": "",
      "resourceName": "kaely test equipment &amp;",
      "cleanupMinutes": 0,
      "eventTypes": [{
        "id": 35,
        "name": "deserunt et",
        "selected": false,
        "text": "deserunt et",
        "value": 35
      }, {
        "id": 36,
        "name": "incididunt irure",
        "selected": false,
        "text": "incididunt irure",
        "value": 36
      }]
    }, 
    {
      "setupMinutes": 0,
      "isTemplate": false,
      "definedDateRange": [{
        "id": 3,
        "name": "2016 Jun 01 to 2016 Jun 03",
        "selected": false,
        "parent_id": 4,
        "text": "2016 Jun 01 to 2016 Jun 03",
        "value": 3
      }, {
        "id": 4,
        "name": "2016 Jun 16 to 2016 Jun 20",
        "selected": false,
        "parent_id": 1,
        "text": "2016 Jun 16 to 2016 Jun 20",
        "value": 4
      }],
      "resourceType": 0,
      "resourceID": 3,
      "rentalBlock": [],
      "bookingDetail": [{
        "recurringPattern": 'recurring',
        "currentEvent": true,
        "recurringExceptions": [],
        "hasRecurring": false,
        "baseBookingID": "pending_775_7160",
        "rentalBlockID": 0,
        "recurringEnabled": false,
        "ignoreConflict": false,
        "startEventTime": "2:00 AM",
        "bookingAssignment": 0,
        "reservationType": 0,
        "resourceBookingID": 0,
        "startEventDate": "2016 Dec 21",
        "pendingRemoveFromRecurringGroup": "",
        "attendance": 2,
        "dateRangeID": 4,
        "recurringReservationGroupID": 0,
        "isDeleteSchedule": false,
        "endEventTime": "3:00 AM",
        "endEventDate": "2016 Dec 21",
        "reservationPeriodUnit": 6,
        "pendingID": "pending_775_7160",
        "isRecurring": false,
        "startEventDatetime": "12/21/2016 2:00 AM",
        "ignoreClosetime": false,
        "ownerPendingReceipt": true,
        "masterFacilityScheduleID": null,
        "transactionID": -1,
        "expanded": false,
        "endEventDatetime": "12/21/2016 3:00 AM",
        "ignoreSkipdate": false
      }],
      "eventTypeID": 6,
      "reservationPeriodUnit": 6,
      "eventType": "'South West Hub",
      "prepCodeID": -1,
      "resourceNumber": "",
      "resourceName": "kaely test equipment &amp;",
      "cleanupMinutes": 0,
      "eventTypes": [{
        "id": 35,
        "name": "deserunt et",
        "selected": false,
        "text": "deserunt et",
        "value": 35
      }, {
        "id": 36,
        "name": "incididunt irure",
        "selected": false,
        "text": "incididunt irure",
        "value": 36
      }]
    }, {
      "setupMinutes": 5,
      "isTemplate": false,
      "definedDateRange": [{
        "id": 3,
        "name": "2016 Jun 01 to 2016 Jun 03",
        "selected": false,
        "parent_id": 4,
        "text": "2016 Jun 01 to 2016 Jun 03",
        "value": 3
      }, {
        "id": 4,
        "name": "2016 Jun 16 to 2016 Jun 20",
        "selected": false,
        "parent_id": 1,
        "text": "2016 Jun 16 to 2016 Jun 20",
        "value": 4
      }],
      "resourceType": 0,
      "resourceID": 6,
      "rentalBlock": [],
      "bookingDetail": [{
        "recurringPattern": 'recurring',
        "currentEvent": true,
        "recurringExceptions": [],
        "hasRecurring": false,
        "baseBookingID": "",
        "rentalBlockID": 0,
        "recurringEnabled": false,
        "ignoreConflict": false,
        "startEventTime": "2:00 AM",
        "bookingAssignment": 0,
        "reservationType": 0,
        "resourceBookingID": 0,
        "startEventDate": "2016 Dec 21",
        "pendingRemoveFromRecurringGroup": "",
        "attendance": 2,
        "dateRangeID": 4,
        "recurringReservationGroupID": 0,
        "isDeleteSchedule": false,
        "endEventTime": "3:00 AM",
        "endEventDate": "2016 Dec 21",
        "reservationPeriodUnit": 6,
        "pendingID": "pending_775_7160",
        "isRecurring": false,
        "startEventDatetime": "12/21/2016 2:00 AM",
        "ignoreClosetime": false,
        "ownerPendingReceipt": true,
        "masterFacilityScheduleID": null,
        "transactionID": -1,
        "expanded": false,
        "endEventDatetime": "12/21/2016 3:00 AM",
        "ignoreSkipdate": false
      }],
      "eventTypeID": -1,
      "reservationPeriodUnit": 6,
      "eventType": "'South West Hub",
      "prepCodeID": -1,
      "resourceNumber": "",
      "resourceName": "kaely test equipment &amp;",
      "cleanupMinutes": 0,
      "eventTypes": [{
        "id": 35,
        "name": "deserunt et",
        "selected": false,
        "text": "deserunt et",
        "value": 35
      }, {
        "id": 36,
        "name": "incididunt irure",
        "selected": false,
        "text": "incididunt irure",
        "value": 36
      }]
    },
    {
      "setupMinutes": 0,
      "isTemplate": true,
      "definedDateRange": [{
        "id": 3,
        "name": "2016 Jun 01 to 2016 Jun 03",
        "selected": false,
        "parent_id": 4,
        "text": "2016 Jun 01 to 2016 Jun 03",
        "value": 3
      }, {
        "id": 4,
        "name": "2016 Jun 16 to 2016 Jun 20",
        "selected": false,
        "parent_id": 1,
        "text": "2016 Jun 16 to 2016 Jun 20",
        "value": 4
      }],
      "resourceType": 0,
      "resourceID": 2,
      "baseBookingID": 2,
      "rentalBlock": [],
      "bookingDetail": [{
        "recurringPattern": 'recurring',
        "id": "13",
        "currentEvent": true,
        "recurringExceptions": [],
        "hasRecurring": false,
        "rentalBlockID": 0,
        "recurringEnabled": false,
        "ignoreConflict": false,
        "startEventTime": "2:00 AM",
        "bookingAssignment": 0,
        "reservationType": 0,
        "resourceBookingID": 11,
        "startEventDate": "2016 Dec 21",
        "pendingRemoveFromRecurringGroup": "",
        "attendance": 2,
        "dateRangeID": 4,
        "recurringReservationGroupID": 0,
        "isDeleteSchedule": false,
        "endEventTime": "3:00 AM",
        "endEventDate": "2016 Dec 21",
        "reservationPeriodUnit": 6,
        "pendingID": "pending_775_7160",
        "isRecurring": false,
        "startEventDatetime": "12/21/2016 2:00 AM",
        "ignoreClosetime": false,
        "ownerPendingReceipt": true,
        "masterFacilityScheduleID": null,
        "transactionID": -1,
        "expanded": false,
        "endEventDatetime": "12/21/2016 3:00 AM",
        "ignoreSkipdate": false
      },
      {
        "recurringPattern": 'recurring',
        "currentEvent": true,
        "recurringExceptions": [],
        "hasRecurring": false,
        "baseBookingID": "13",
        "rentalBlockID": 0,
        "recurringEnabled": false,
        "ignoreConflict": false,
        "startEventTime": "2:00 AM",
        "bookingAssignment": 0,
        "reservationType": 0,
        "resourceBookingID": 11,
        "startEventDate": "2016 Dec 21",
        "pendingRemoveFromRecurringGroup": "fdsasdf",
        "attendance": 2,
        "dateRangeID": 4,
        "recurringReservationGroupID": 0,
        "isDeleteSchedule": false,
        "endEventTime": "3:00 AM",
        "endEventDate": "2016 Dec 21",
        "reservationPeriodUnit": 6,
        "pendingID": "pending_775_71601",
        "isRecurring": false,
        "startEventDatetime": "12/21/2016 2:00 AM",
        "ignoreClosetime": false,
        "ownerPendingReceipt": true,
        "masterFacilityScheduleID": null,
        "transactionID": -1,
        "expanded": false,
        "endEventDatetime": "12/21/2016 3:00 AM",
        "ignoreSkipdate": false
      },
      {
        "recurringPattern": 'recurring',
        "currentEvent": true,
        "recurringExceptions": [],
        "hasRecurring": false,
        "baseBookingID": "13",
        "rentalBlockID": 0,
        "recurringEnabled": false,
        "ignoreConflict": false,
        "startEventTime": "2:00 AM",
        "bookingAssignment": 0,
        "reservationType": 0,
        "resourceBookingID": 11,
        "startEventDate": "2016 Dec 21",
        "pendingRemoveFromRecurringGroup": "",
        "attendance": 2,
        "dateRangeID": 4,
        "recurringReservationGroupID": 0,
        "isDeleteSchedule": false,
        "endEventTime": "3:00 AM",
        "endEventDate": "2016 Dec 21",
        "reservationPeriodUnit": 6,
        "pendingID": "pending_775_71601",
        "isRecurring": false,
        "startEventDatetime": "12/21/2016 2:00 AM",
        "ignoreClosetime": false,
        "ownerPendingReceipt": true,
        "masterFacilityScheduleID": null,
        "transactionID": -1,
        "expanded": false,
        "endEventDatetime": "12/21/2016 3:00 AM",
        "ignoreSkipdate": false
      },
    ],
      "eventTypeID": 36,
      "reservationPeriodUnit": 6,
      "eventType": "'South West Hub",
      "prepCodeID": -1,
      "resourceNumber": "",
      "resourceName": "kaely test equipment &amp;",
      "cleanupMinutes": 0,
      "eventTypes": [{
        "id": 35,
        "name": "deserunt et",
        "selected": false,
        "text": "deserunt et",
        "value": 35
      }, {
        "id": 36,
        "name": "incididunt irure",
        "selected": false,
        "text": "incididunt irure",
        "value": 36
      }]
    }]
  },
  isBookingChanged: false,
  backFromPermitDetailPage: false,
  display: false,
  templateState: 'has_template',
  recurring: {
    base: {
      resourceIndex: 0,
      bookingIndex: 0
    },
    clear: ''
  },
  deleteBookings: [],
  currentApplyBaseBooking: {resourceIndex: 0, bookingIndex: 0}
};

export default bookingInfo;