const recurringBookingInfo = {
  eventTypes: [],
  scheduleTypes: [],
  prepCodeList: [{
    id: 1
  }, {
    id: 2
  }],
  setUpList: [],
  cleanUpList: [],
  permitBookingList: [
    {
      permitID: -1,
      setupMinutes: 0,
      resourceType: 0,
      resourceID: 1,
      rentalBlock: [],
      eventTypeID: 6,
      reservationPeriodUnit: 2,
      eventType: "event type 1",
      prepCodeID: 10,
      resourceNumber: "1",
      resourceName: "resourceName 1",
      cleanupMinutes: 5,
      bookingDetail: [{
        "currentEvent": true,
        "recurringExceptions": [],
        "bookingIdentifier": "pending_1424_4484",
        "hasRecurring": true,
        "baseBookingID": "",
        "rentalBlockID": 0,
        "recurringEnabled": false,
        "ignoreConflict": false,
        "startEventTime": "2:00 AM",
        "bookingAssignment": 0,
        "reservationType": 0,
        "resourceBookingID": 0,
        "startEventDate": "2016 Dec 21",
        "enableIgnoreConflict": false,
        "pendingRemoveFromRecurringGroup": "",
        "attendance": 3,
        "dateRangeID": 0,
        "recurringReservationGroupID": 0,
        "isDeleteSchedule": false,
        "endEventTime": "3:00 AM",
        "endEventDate": "2016 Dec 21",
        "errorResults": [],
        "reservationPeriodUnit": 2,
        "pendingID": "pending_1424_4484",
        "isRecurring": false,
        "masterBookingIdentifier": "pending_1424_4484",
        "recurringPattern": {
          "count": 5,
          "frequency": 1,
          "type": 1
        },
        "startEventDatetime": "12/21/2016 2:00 AM",
        "ignoreClosetime": false,
        "ownerPendingReceipt": true,
        "masterFacilityScheduleID": 117712,
        "transactionID": -1,
        "expanded": true,
        "endEventDatetime": "12/21/2016 3:00 AM",
        "ignoreConflictType": "not_show_ignore",
        "ignoreSkipdate": false
      }]
    }
  ],
  pendingBookingList: [],
  error: {
    code: '1050',
    clientMessages: [],
    serverMessages: [],
    conflictMessage: "",
    entity: {
      eventName: false,
      scheduleTypeID: false,
      overrideRentalBlockTimeError: [],
      eventResource: [{
        "resourceID": 1,
        "resourceName": "kaely test equipment &amp;",
        "eventTypeID": true,
        "bookingDetail": [{
          "pendingID": "pending_1424_4485",
          "resourceBookingID": 0,
          "errors": {
            "conflictType": "startEventTime"
          }
        }]
      }]
    }
  },
  data: {
    permitID: -1,
    eventName: '',
    scheduleTypeID: -1,
    scheduleType: '',
    checkForWaitlistConflict: true,
    eventResource: [ {
      "setupMinutes": 3,
      "definedDateRange": [],
      "resourceType": 0,
      "resourceID": 1,
      "rentalBlock": [],
      "bookingDetail": [{
        "currentEvent": true,
        "recurringExceptions": [],
        "bookingIdentifier": "pending_1424_4484",
        "hasRecurring": true,
        "baseBookingID": "",
        "rentalBlockID": 0,
        "recurringEnabled": false,
        "ignoreConflict": false,
        "startEventTime": "2:00 AM",
        "bookingAssignment": 0,
        "reservationType": 0,
        "resourceBookingID": 0,
        "startEventDate": "2016 Dec 21",
        "enableIgnoreConflict": false,
        "pendingRemoveFromRecurringGroup": "",
        "attendance": 3,
        "dateRangeID": 0,
        "recurringReservationGroupID": 0,
        "isDeleteSchedule": false,
        "endEventTime": "3:00 AM",
        "endEventDate": "2016 Dec 21",
        "errorResults": [],
        "reservationPeriodUnit": 2,
        "pendingID": "pending_1424_4484",
        "isRecurring": false,
        "masterBookingIdentifier": "pending_1424_4484",
        "recurringPattern": {
          "count": 5,
          "frequency": 1,
          "type": 1
        },
        "startEventDatetime": "12/21/2016 2:00 AM",
        "ignoreClosetime": false,
        "ownerPendingReceipt": true,
        "masterFacilityScheduleID": 117712,
        "transactionID": -1,
        "expanded": true,
        "endEventDatetime": "12/21/2016 3:00 AM",
        "ignoreConflictType": "not_show_ignore",
        "ignoreSkipdate": false
      }, {
        "currentEvent": true,
        "recurringExceptions": [],
        "bookingIdentifier": "pending_1424_4485",
        "hasRecurring": false,
        "baseBookingID": "pending_1424_4484",
        "rentalBlockID": 0,
        "recurringEnabled": true,
        "ignoreConflict": false,
        "startEventTime": "2:00 AM",
        "bookingAssignment": 0,
        "reservationType": 0,
        "resourceBookingID": 0,
        "startEventDate": "2016 Dec 21",
        "enableIgnoreConflict": false,
        "pendingRemoveFromRecurringGroup": "",
        "attendance": 3,
        "dateRangeID": 0,
        "recurringReservationGroupID": 0,
        "isDeleteSchedule": false,
        "endEventTime": "3:00 AM",
        "endEventDate": "2016 Dec 21",
        "errorResults": [],
        "reservationPeriodUnit": 2,
        "pendingID": "pending_1424_4485",
        "isRecurring": true,
        "startEventDatetime": "12/21/2016 2:00 AM",
        "ignoreClosetime": false,
        "ownerPendingReceipt": true,
        "masterFacilityScheduleID": null,
        "transactionID": -1,
        "expanded": false,
        "endEventDatetime": "12/21/2016 3:00 AM",
        "ignoreConflictType": "not_show_ignore",
        "ignoreSkipdate": false
      }, {
        "currentEvent": true,
        "recurringExceptions": [],
        "bookingIdentifier": "pending_1424_4486",
        "hasRecurring": false,
        "baseBookingID": "pending_1424_4484",
        "rentalBlockID": 0,
        "recurringEnabled": true,
        "ignoreConflict": false,
        "startEventTime": "2:00 AM",
        "bookingAssignment": 0,
        "reservationType": 0,
        "resourceBookingID": 0,
        "startEventDate": "2016 Dec 21",
        "enableIgnoreConflict": false,
        "pendingRemoveFromRecurringGroup": "",
        "attendance": 3,
        "dateRangeID": 0,
        "recurringReservationGroupID": 0,
        "isDeleteSchedule": false,
        "endEventTime": "3:00 AM",
        "endEventDate": "2016 Dec 21",
        "errorResults": [],
        "reservationPeriodUnit": 2,
        "pendingID": "pending_1424_4486",
        "isRecurring": true,
        "startEventDatetime": "12/21/2016 2:00 AM",
        "ignoreClosetime": false,
        "ownerPendingReceipt": true,
        "masterFacilityScheduleID": null,
        "transactionID": -1,
        "expanded": false,
        "endEventDatetime": "12/21/2016 3:00 AM",
        "ignoreConflictType": "not_show_ignore",
        "ignoreSkipdate": false
      }, {
        "currentEvent": true,
        "recurringExceptions": [],
        "bookingIdentifier": "pending_1424_4487",
        "hasRecurring": false,
        "baseBookingID": "pending_1424_4484",
        "rentalBlockID": 0,
        "recurringEnabled": true,
        "ignoreConflict": false,
        "startEventTime": "2:00 AM",
        "bookingAssignment": 0,
        "reservationType": 0,
        "resourceBookingID": 0,
        "startEventDate": "2016 Dec 21",
        "enableIgnoreConflict": false,
        "pendingRemoveFromRecurringGroup": "",
        "attendance": 3,
        "dateRangeID": 0,
        "recurringReservationGroupID": 0,
        "isDeleteSchedule": false,
        "endEventTime": "3:00 AM",
        "endEventDate": "2016 Dec 21",
        "errorResults": [],
        "reservationPeriodUnit": 2,
        "pendingID": "pending_1424_4487",
        "isRecurring": true,
        "startEventDatetime": "12/21/2016 2:00 AM",
        "ignoreClosetime": false,
        "ownerPendingReceipt": true,
        "masterFacilityScheduleID": null,
        "transactionID": -1,
        "expanded": false,
        "endEventDatetime": "12/21/2016 3:00 AM",
        "ignoreConflictType": "not_show_ignore",
        "ignoreSkipdate": false
      }, {
        "currentEvent": true,
        "recurringExceptions": [],
        "bookingIdentifier": "pending_1424_4488",
        "hasRecurring": false,
        "baseBookingID": "pending_1424_4484",
        "rentalBlockID": 0,
        "recurringEnabled": true,
        "ignoreConflict": false,
        "startEventTime": "2:00 AM",
        "bookingAssignment": 0,
        "reservationType": 0,
        "resourceBookingID": 0,
        "startEventDate": "2016 Dec 21",
        "enableIgnoreConflict": false,
        "pendingRemoveFromRecurringGroup": "",
        "attendance": 3,
        "dateRangeID": 0,
        "recurringReservationGroupID": 0,
        "isDeleteSchedule": false,
        "endEventTime": "3:00 AM",
        "endEventDate": "2016 Dec 21",
        "errorResults": [],
        "reservationPeriodUnit": 2,
        "pendingID": "pending_1424_4488",
        "isRecurring": true,
        "startEventDatetime": "12/21/2016 2:00 AM",
        "ignoreClosetime": false,
        "ownerPendingReceipt": true,
        "masterFacilityScheduleID": null,
        "transactionID": -1,
        "expanded": false,
        "endEventDatetime": "12/21/2016 3:00 AM",
        "ignoreConflictType": "not_show_ignore",
        "ignoreSkipdate": false
      }],
      "eventTypeID": 36,
      "reservationPeriodUnit": 2,
      "eventType": "'South West Hub",
      "prepCodeID": 1,
      "resourceNumber": "",
      "resourceName": "resourceType &apm;",
      "cleanupMinutes": 5,
      "eventTypes": [{
        "id": 34,
        "name": "South West Hub",
        "selected": false,
        "text": "South West Hub",
        "value": 34
      }, {
        "id": 35,
        "name": "deserunt et",
        "selected": false,
        "text": "deserunt et",
        "value": 35
      }, {
        "id": 36,
        "name": "incididunt irure",
        "selected": false,
        "text": "incididunt irure",
        "value": 36
      }, {
        "id": 56,
        "name": "lillian_eventype",
        "selected": false,
        "text": "lillian_eventype",
        "value": 56
      }]
    }]
  },
  isBookingChanged: false,
  backFromPermitDetailPage: false,
  display: false,
  templateState: 'no_template',
  deleteBookings: []
};

export default recurringBookingInfo;
