export const FETCH_PERMIT_CONTRACT_SUCCESS = 'FETCH_PERMIT_CONTRACT_SUCCESS';
export const FETCH_PERMIT_SCHEDULE_SUCCESS = 'FETCH_PERMIT_SCHEDULE_SUCCESS';
export const FETCH_AMENDMENT_SUCCESS = 'FETCH_AMENDMENT_SUCCESS';
export const GENERATE_PERMIT_CONTRACT_PDF_SUCCESS = 'GENERATE_PERMIT_CONTRACT_PDF_SUCCESS';
export const EMAIL_PERMIT_CONTRACT_SUCCESS = 'EMAIL_PERMIT_CONTRACT_SUCCESS';
