const PREFIX = 'Cart/Balance/';

export const BALANCE_UI_LIST = `${PREFIX}BALANCE_UI_LIST`;
export const BALANCE_UI_MESSAGE = `${PREFIX}BALANCE_UI_MESSAGE`;
export const BALANCE_ON_VALIDATION = `${PREFIX}BALANCE_ON_VALIDATION`;
export const BALANCE_ON_CLEAR_INFO = `${PREFIX}BALANCE_ON_CLEAR_INFO`;
export const BALANCE_ON_UPDATE_LIST = `${PREFIX}BALANCE_ON_UPDATE_LIST`;
