'use strict';Object.defineProperty(exports, "__esModule", { value: true });var ALPHA = exports.ALPHA = 'alpha';
var DIGITS = exports.DIGITS = 'digits';
var EMAIL = exports.EMAIL = 'email';
var IP = exports.IP = 'ip';
var MAX = exports.MAX = 'max';
var MAX_LENGTH = exports.MAX_LENGTH = 'maxLength';
var MIN = exports.MIN = 'min';
var MIN_LENGTH = exports.MIN_LENGTH = 'minLength';
var RANGE = exports.RANGE = 'range';
var RANGE_LENGTH = exports.RANGE_LENGTH = 'rangeLength';
var REQUIRED = exports.REQUIRED = 'required';
var URL = exports.URL = 'url';
var ZIP_CODE = exports.ZIP_CODE = 'zipcode';