#!groovy

node {
  currentBuild.displayName = sh(returnStdout: true, script: 'cat package.json | grep version | sed \'s/"//g\' | awk -F \': \' \'{print $2}\' | sed s/,//g').trim() // the name of the current Jenkins job

  gitlabCommitStatus {
    currentBuild.result = "SUCCESS"

    stage('Checkout') {
      checkout scm
    }

    stage('Install') {
      sh 'yarn'
    }

    stage('Lint') {
      sh 'npm run lint'
    }

    stage('Test') {
      try {
        sh 'npm test'
      } catch (err) {
        currentBuild.result = "FAILURE"
        error 'Testing failed'
        throw err
      } finally {
        publishHTML([allowMissing: true, alwaysLinkToLastBuild: true, keepAll: false, reportDir: 'coverage/lcov-report/', reportFiles: 'index.html', reportName: 'LCOV Report'])
      }
    }
  }
}
