'use strict';Object.defineProperty(exports, "__esModule", { value: true });var _extends2 = require('babel-runtime/helpers/extends');var _extends3 = _interopRequireDefault(_extends2);var _objectWithoutProperties2 = require('babel-runtime/helpers/objectWithoutProperties');var _objectWithoutProperties3 = _interopRequireDefault(_objectWithoutProperties2);var _dialog = require('./dialog');var _dialog2 = _interopRequireDefault(_dialog);function _interopRequireDefault(obj) {return obj && obj.__esModule ? obj : { default: obj };}

/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @function confirm
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @description Pops up confirmation dialogbox, and waits user's response in async mode.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @returns {Promise} Returns a promise where the success function
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * is called if the user choose the OK action,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * or the failed function is called if the user choose the Cancel action.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @param {string} message -
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * A message string to indicate or query user's choice.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @param {object} [options] - Options that determine the behaviors of the confirmation.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @param {string} [options.title=Confirm] - Title text of the confirmation dialogbox.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @param {boolean} [options.showCancel=false] -
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * Whether to display the cancel button. By default, only the OK button is displayed.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @param {string} [options.cancelText=Cancel] -
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * The text of the Cancel button.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @param {string} [options.confirmText=OK] -
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * The text of the OK button.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @param {string} [options.className] - Custom class name
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @memberof DialogBox
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @example
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * import { confirm } from 'react-base-ui/lib/services/dialog'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * confirm('Session time out');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * //or
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * confirm('Are you sure you want to delete the transaction?',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * {showCancel: true, cancelText: 'DELETE'})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * .then(()=>{//...do delete...})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * .catch(()=>{//...canceled...});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
var confirm = function confirm(message) {var options = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};var _options$title =
  options.title,title = _options$title === undefined ? 'Confirm' : _options$title,value = options.value,rest = (0, _objectWithoutProperties3.default)(options, ['title', 'value']);

  return (0, _dialog2.default)(title, null, { message: message, value: value }, (0, _extends3.default)({}, rest));
};exports.default =

confirm;module.exports = exports['default'];