#!groovy

node {
  currentBuild.displayName = sh(returnStdout: true, script: 'cat package.json | grep version | sed \'s/"//g\' | awk -F \': \' \'{print $2}\' | sed s/,//g').trim() // the name of the current Jenkins job

  gitlabCommitStatus {
    currentBuild.result = "SUCCESS"

    stage('Checkout') {
      checkout scm
    }

    stage('Install') {
      sh 'npm ci'
    }

    stage('Lint') {
      sh 'npm run lint'
    }

    stage('Build') {
      try {
        sh 'npm run build'
      } catch (err) {
        currentBuild.result = "FAILURE"
        error 'Transpile LESS -> CSS failed'
        throw err
      }
    }
  }
}
